
import java.awt.Choice;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchBy.java
 *
 * Created on Sep 7, 2014, 9:10:10 AM
 */
/**
 *
 * @author Sir
 */
public class SearchBy extends javax.swing.JFrame {

    String itemname,itemvalue;
    /** Creates new form SearchBy */
    public SearchBy() {
        initComponents();
        setSize(630,300);
        setLocationRelativeTo(this);
          setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        
        choice1.add("Select");
        choice1.add("firstname");
        choice1.add("lastname");
        choice1.add("nickname");
        choice1.add("mobile1");
        choice1.add("mobile2");
        choice1.add("homeContact");
         choice1.add("city");
        choice1.add("gmail");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
       
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("SEARCH CONTACT BY");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 210, 190, 23);

        choice1.setName("choice1"); // NOI18N
        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });
        getContentPane().add(choice1);
        choice1.setBounds(230, 240, 230, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SearchBanner.jpg"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 614, 276);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
         //Choice c=(Choice)evt.getSource();
         //itemname=c.getSelectedItem();
        itemname=((Choice)evt.getSource()).getSelectedItem();
        System.out.println("u have selected:"+itemname);
        
        itemvalue=JOptionPane.showInputDialog("Enter "+itemname);
        if(itemvalue==null)
        {
            
        }
        else
        {
        System.out.println("u have entered :"+itemvalue); 
        GetValues obj=new GetValues(itemname,itemvalue);
        obj.setVisible(true);
        }
    }//GEN-LAST:event_choice1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SearchBy().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
